### ISSUE TITLE
Logs not being saved

### ISSUE THREAD

**Issue by mmoisse** [remche/zero-to-shinyproxy#12]
I get the following warning message when starting shinyproxy

```
java.nio.file.AccessDeniedException: /opt/shinyproxy/./container-logs
```

**Comment by mmoisse** [comment]
I found a solution to it by mounting a persistent storage to shiny proxy and editing `shinyproxy/templates/deployment.yaml` although the solution it's hardcoded.

```
spec:
  template:
    spec:
      containers:
          volumeMounts:
          - name: application-conf
            mountPath: /opt/shinyproxy/application.yml
            subPath: application.yml
          - name: shinyproxy-persistent-storage
            mountPath: /srv/shinyproxy
```

```
      volumes:
      - name: application-conf
        configMap:
          name: shinyproxy
      - name: shinyproxy-persistent-storage
        persistentVolumeClaim:
          claimName: shinyproxy-volumeclaim
      securityContext:
        fsGroup: 1000
```
